version: '3.8'
services:
  myapp:
    image: test_app:latest
    ports:
      - "9000:9000"
    environment:
      UVICORN_HOST: "0.0.0.0"
      UVICORN_PORT: "9000"
    networks:
          - app-network

    test:
      build:
        context: git://github.com/yourusername/test-repository#main
        dockerfile: Dockerfile
      depends_on:
        - myapp
      networks:
        - app-network

  networks:
    app-network:
      driver: bridge